// GENERATED FILE - DO NOT EDIT BY HAND.
// Generator: tkrtool-iron:scripts/mirror/build-aqp-production-bundle.mjs
//   regenerate: node scripts/mirror/build-aqp-production-bundle.mjs --prestate <PRODUCTION aqp-1 pre-state artifact.json>
//   verify:     node scripts/mirror/build-aqp-production-bundle.mjs --prestate <same artifact> --check
//   (READY: generation and --check require clean, tracked generation sources at the tooling commit META.generatorCommit)
// PRODUCTION_BUNDLE_SHA256 = sha256 of the UTF-8 bytes of PRODUCTION_BUNDLE_SQL. The broker sends these exact bytes, once.
// STATUS: READY (embeds the exact PRODUCTION pre-state; any drift aborts the transaction with TK_PRESTATE_DRIFT).

export const PRODUCTION_BUNDLE_SQL: string = [
  "BEGIN ISOLATION LEVEL READ COMMITTED;",
  "SET LOCAL search_path = pg_catalog, pg_temp;",
  "SET LOCAL DateStyle = 'ISO, MDY';",
  "SET LOCAL IntervalStyle = 'postgres';",
  "SET LOCAL TimeZone = 'UTC';",
  "SET LOCAL bytea_output = 'hex';",
  "SET LOCAL extra_float_digits = '0';",
  "SET LOCAL lock_timeout = '5s';",
  "SET LOCAL statement_timeout = '120s';",
  "LOCK TABLE supabase_migrations.schema_migrations IN SHARE ROW EXCLUSIVE MODE;",
  "DO $tk_guard$",
  "DECLARE v text[]; cur jsonb;",
  "BEGIN",
  "  IF pg_catalog.current_setting('search_path') IS DISTINCT FROM 'pg_catalog, pg_temp' THEN RAISE EXCEPTION 'TK_SEARCH_PATH: executor search_path not pinned'; END IF;",
  "  SELECT coalesce(pg_catalog.array_agg(version ORDER BY version COLLATE \"C\"), '{}') INTO v FROM supabase_migrations.schema_migrations;",
  "  IF '20260929000000' = ANY(v) THEN RAISE EXCEPTION 'TK_REPLAY_REFUSED: % is already recorded', '20260929000000'; END IF;",
  "  IF v IS DISTINCT FROM ARRAY['20260827000000','20260827000001','202608270000015','20260827000002','20260827000003','20260828000000','20260831000000','20260908000000','20260917000000','20260917000001','20260917000002','20260917000003','20260922000000','20260927000000']::text[] THEN RAISE EXCEPTION 'TK_LEDGER_IDENTITY_MISMATCH: the ledger is not the recorded 14-version Production pre-state'; END IF;",
  "  cur := (pg_catalog.json_build_object(",
  " 'database', pg_catalog.current_database(),",
  " 'serverVersionNum', pg_catalog.current_setting('server_version_num'),",
  " 'searchPath', pg_catalog.current_setting('search_path'),",
  " 'ledgerColumns', (SELECT coalesce(pg_catalog.json_agg(pg_catalog.json_build_object('name', (column_name)::pg_catalog.text, 'type', (data_type)::pg_catalog.text, 'nullable', (is_nullable)::pg_catalog.text) ORDER BY ordinal_position), '[]') FROM information_schema.columns WHERE table_schema = 'supabase_migrations' AND table_name = 'schema_migrations'),",
  " 'ledgerVersions', (SELECT coalesce(pg_catalog.json_agg(version ORDER BY version COLLATE \"C\"), '[]') FROM supabase_migrations.schema_migrations),",
  " 'ledgerPriorForwardSha256', (SELECT pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(statements[1], 'UTF8')), 'hex') FROM supabase_migrations.schema_migrations WHERE version = '20260927000000'),",
  " 'overloads', (SELECT coalesce(pg_catalog.json_agg(pg_catalog.json_build_object(",
  "     'signature', (p.proname)::pg_catalog.text || '(' || pg_catalog.oidvectortypes(p.proargtypes) || ')', 'defSha256', pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(pg_catalog.pg_get_functiondef(p.oid), 'UTF8')), 'hex'), 'securityDefiner', p.prosecdef,",
  "     'acl', (SELECT pg_catalog.string_agg(a::pg_catalog.text, ',' ORDER BY a::pg_catalog.text COLLATE \"C\") FROM pg_catalog.unnest(p.proacl) AS a), 'owner', pg_catalog.pg_get_userbyid(p.proowner)::pg_catalog.text) ORDER BY pg_catalog.oidvectortypes(p.proargtypes) COLLATE \"C\"), '[]')",
  "   FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'public' AND p.proname = 'approve_quote_public'),",
  " 'dependents', (SELECT coalesce(pg_catalog.json_agg(x ORDER BY x COLLATE \"C\"), '[]') FROM (",
  "     SELECT 'dep:' || (d.deptype)::pg_catalog.text || ':' || pg_catalog.pg_describe_object(d.classid, d.objid, d.objsubid) AS x FROM pg_catalog.pg_depend d WHERE d.refclassid = 'pg_catalog.pg_proc'::pg_catalog.regclass AND d.deptype IN ('n', 'a') AND d.refobjid IN (SELECT p.oid FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'public' AND p.proname = 'approve_quote_public')",
  "     UNION ALL SELECT 'trg:' || (t.tgname)::pg_catalog.text FROM pg_catalog.pg_trigger t WHERE t.tgfoid IN (SELECT p.oid FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'public' AND p.proname = 'approve_quote_public')",
  "     UNION ALL SELECT 'evt:' || (e.evtname)::pg_catalog.text FROM pg_catalog.pg_event_trigger e WHERE e.evtfoid IN (SELECT p.oid FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'public' AND p.proname = 'approve_quote_public')) s),",
  " 'canonical', (SELECT pg_catalog.json_build_object('defSha256', pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(pg_catalog.pg_get_functiondef(p.oid), 'UTF8')), 'hex'), 'acl', (SELECT pg_catalog.string_agg(a::pg_catalog.text, ',' ORDER BY a::pg_catalog.text COLLATE \"C\") FROM pg_catalog.unnest(p.proacl) AS a), 'owner', pg_catalog.pg_get_userbyid(p.proowner)::pg_catalog.text, 'securityDefiner', p.prosecdef, 'config', p.proconfig)",
  "   FROM pg_catalog.pg_proc p WHERE p.oid = pg_catalog.to_regprocedure('public.public_approve_quote(uuid,text)')),",
  " 'schemaObjects', (SELECT coalesce(pg_catalog.json_agg(o ORDER BY o COLLATE \"C\"), '[]') FROM (",
  "   SELECT 'rel:' || (n.nspname)::pg_catalog.text || '.' || (c.relname)::pg_catalog.text || ':' || (c.relkind)::pg_catalog.text AS o FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname IN ('public', 'auth', 'storage') AND c.relkind IN ('r', 'p', 'v', 'm', 'f', 'S', 'i')",
  "   UNION ALL SELECT 'fn:' || (n.nspname)::pg_catalog.text || '.' || (p.proname)::pg_catalog.text || '(' || pg_catalog.oidvectortypes(p.proargtypes) || ')' FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'public'",
  "   UNION ALL SELECT 'pol:' || (schemaname)::pg_catalog.text || '.' || (tablename)::pg_catalog.text || '.' || (policyname)::pg_catalog.text FROM pg_catalog.pg_policies WHERE schemaname IN ('public', 'storage')",
  "   UNION ALL SELECT 'trg:' || (n.nspname)::pg_catalog.text || '.' || (c.relname)::pg_catalog.text || '.' || (t.tgname)::pg_catalog.text FROM pg_catalog.pg_trigger t JOIN pg_catalog.pg_class c ON c.oid = t.tgrelid JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace WHERE NOT t.tgisinternal AND n.nspname IN ('public', 'auth', 'storage')",
  "   UNION ALL SELECT 'con:' || (n.nspname)::pg_catalog.text || '.' || (c.conname)::pg_catalog.text FROM pg_catalog.pg_constraint c JOIN pg_catalog.pg_namespace n ON n.oid = c.connamespace WHERE n.nspname = 'public'",
  " ) s),",
  " 'publicFunctionDefsSha256', (SELECT pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(coalesce(pg_catalog.string_agg((p.proname)::pg_catalog.text || '(' || pg_catalog.oidvectortypes(p.proargtypes) || ')=' || pg_catalog.md5(pg_catalog.pg_get_functiondef(p.oid)) || ':' || (coalesce(p.proacl::pg_catalog.text, ''))::pg_catalog.text, E'\\n' ORDER BY p.proname COLLATE \"C\", pg_catalog.oidvectortypes(p.proargtypes) COLLATE \"C\"), ''), 'UTF8')), 'hex') FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'public' AND p.prokind IN ('f', 'p') AND p.proname <> 'approve_quote_public'),",
  " 'publicColumnsSha256', (SELECT pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(coalesce(pg_catalog.string_agg((table_name)::pg_catalog.text || '.' || (column_name)::pg_catalog.text || ':' || (data_type)::pg_catalog.text || ':' || (is_nullable)::pg_catalog.text || ':' || (coalesce(column_default::pg_catalog.text, ''))::pg_catalog.text, E'\\n' ORDER BY table_name COLLATE \"C\", column_name COLLATE \"C\"), ''), 'UTF8')), 'hex') FROM information_schema.columns WHERE table_schema = 'public'),",
  " 'publicTableAclSha256', (SELECT pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(coalesce(pg_catalog.string_agg((c.relname)::pg_catalog.text || ':' || (c.relrowsecurity)::pg_catalog.text || ':' || (coalesce(c.relacl::pg_catalog.text, ''))::pg_catalog.text, E'\\n' ORDER BY c.relname COLLATE \"C\"), ''), 'UTF8')), 'hex') FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p', 'v', 'm'))",
  "))::jsonb;",
  "  IF cur IS DISTINCT FROM '{\"database\":\"postgres\",\"serverVersionNum\":\"170006\",\"searchPath\":\"pg_catalog, pg_temp\",\"ledgerColumns\":[{\"name\":\"version\",\"type\":\"text\",\"nullable\":\"NO\"},{\"name\":\"statements\",\"type\":\"ARRAY\",\"nullable\":\"YES\"},{\"name\":\"name\",\"type\":\"text\",\"nullable\":\"YES\"}],\"ledgerVersions\":[\"20260827000000\",\"20260827000001\",\"202608270000015\",\"20260827000002\",\"20260827000003\",\"20260828000000\",\"20260831000000\",\"20260908000000\",\"20260917000000\",\"20260917000001\",\"20260917000002\",\"20260917000003\",\"20260922000000\",\"20260927000000\"],\"ledgerPriorForwardSha256\":\"97d2017ed55ce06ca4683973adc69e48372d87a74e9c60e5a26d8b3a60a1d729\",\"overloads\":[{\"signature\":\"approve_quote_public(uuid)\",\"defSha256\":\"b50d1c880ba4f260eeea7925c33ca49d1d2dbed76730b4ba69f3b7af2b0a9a31\",\"securityDefiner\":true,\"acl\":\"=X/postgres,anon=X/postgres,authenticated=X/postgres,postgres=X/postgres,service_role=X/postgres\",\"owner\":\"postgres\"},{\"signature\":\"approve_quote_public(uuid, text)\",\"defSha256\":\"e36067ab64ff0c8d52a5eb200e175565a160ba3cac1880b6924573197cf17d7b\",\"securityDefiner\":true,\"acl\":\"=X/postgres,anon=X/postgres,authenticated=X/postgres,postgres=X/postgres,service_role=X/postgres\",\"owner\":\"postgres\"}],\"dependents\":[],\"canonical\":{\"defSha256\":\"eab641c566ec6776c0f3a389e6ba80d7e7f204d1479194f681ca51e838aeb855\",\"acl\":\"anon=X/postgres,authenticated=X/postgres,postgres=X/postgres\",\"owner\":\"postgres\",\"securityDefiner\":true,\"config\":[\"search_path=public, pg_temp\"]},\"schemaObjects\":[\"con:public.business_quote_sequences_pkey\",\"con:public.business_quote_sequences_user_id_fkey\",\"con:public.business_settings_pkey\",\"con:public.business_settings_user_id_fkey\",\"con:public.business_settings_user_id_unique\",\"con:public.chat_logs_pkey\",\"con:public.clients_pkey\",\"con:public.clients_user_id_fkey\",\"con:public.expenses_pkey\",\"con:public.expenses_user_id_fkey\",\"con:public.quote_attachments_pkey\",\"con:public.quote_attachments_quote_id_fkey\",\"con:public.quote_item_measurements_item_quote_fkey\",\"con:public.quote_item_measurements_pkey\",\"con:public.quote_item_measurements_quote_id_fkey\",\"con:public.quote_items_calculation_method_check\",\"con:public.quote_items_id_quote_id_key\",\"con:public.quote_items_pkey\",\"con:public.quote_items_quantity_source_check\",\"con:public.quote_items_quote_id_fkey\",\"con:public.quote_items_section_quote_fkey\",\"con:public.quote_sections_id_quote_id_key\",\"con:public.quote_sections_pkey\",\"con:public.quote_sections_quote_id_fkey\",\"con:public.quote_storage_gc_bucket_id_storage_path_key\",\"con:public.quote_storage_gc_pkey\",\"con:public.quote_storage_gc_user_id_fkey\",\"con:public.quotecode_documents_pkey\",\"con:public.quotes_client_id_fkey\",\"con:public.quotes_pkey\",\"con:public.quotes_user_id_fkey\",\"con:public.quotes_user_quote_number_unique\",\"con:public.services_pkey\",\"con:public.trial_reminder_deliveries_attempt_check\",\"con:public.trial_reminder_deliveries_pkey\",\"con:public.trial_reminder_deliveries_stage_check\",\"con:public.trial_reminder_deliveries_status_check\",\"con:public.trial_reminder_deliveries_user_id_fkey\",\"fn:public.allocate_quote_number(uuid)\",\"fn:public.approve_quote_public(uuid)\",\"fn:public.approve_quote_public(uuid, text)\",\"fn:public.claim_trial_reminder(uuid, text)\",\"fn:public.complete_trial_reminder(uuid, text, uuid, text, text, text)\",\"fn:public.enqueue_quote_attachment_gc()\",\"fn:public.guard_business_settings_plan_trial()\",\"fn:public.guard_quote_child_immutability()\",\"fn:public.guard_quote_immutability()\",\"fn:public.guard_quote_immutability_delete()\",\"fn:public.handle_user_migration()\",\"fn:public.increment_quote_views(uuid)\",\"fn:public.is_admin()\",\"fn:public.is_issuer_tenant_member(uuid)\",\"fn:public.is_super_admin()\",\"fn:public.protect_quote_number_immutability()\",\"fn:public.public_approve_quote(uuid, text)\",\"fn:public.public_increment_quote_view(uuid)\",\"fn:public.quote_acceptance_expired(date, text, timestamp with time zone)\",\"fn:public.save_quote_atomic(uuid, boolean, jsonb, jsonb, jsonb, jsonb, jsonb, uuid[], uuid[], jsonb, jsonb, uuid[])\",\"fn:public.save_quote_atomic_version()\",\"fn:public.save_quote_structured(uuid, jsonb, jsonb, jsonb, uuid[], uuid[])\",\"fn:public.unsection_quote_items_on_section_delete()\",\"pol:public.business_quote_sequences.Super admins can view all quote sequences\",\"pol:public.business_settings.Admins can view all business settings\",\"pol:public.business_settings.Owners can manage business settings\",\"pol:public.business_settings.Restrict business_settings insert to role=user\",\"pol:public.business_settings.Restrict business_settings insert to safe free or legitimate tr\",\"pol:public.business_settings.Super admins can update all business settings\",\"pol:public.business_settings.Super admins can view all business settings\",\"pol:public.business_settings.Users can insert own settings\",\"pol:public.business_settings.Users can update own settings\",\"pol:public.chat_logs.Super admins can view all chat logs\",\"pol:public.clients.Owners can manage clients\",\"pol:public.expenses.Owners can manage expenses\",\"pol:public.expenses.Users can delete own expenses\",\"pol:public.expenses.Users can insert own expenses\",\"pol:public.expenses.Users can manage their own expenses\",\"pol:public.expenses.Users can update own expenses\",\"pol:public.expenses.Users can view own expenses\",\"pol:public.expenses.Users manage their own expenses\",\"pol:public.quote_attachments.Owners can manage quote attachments\",\"pol:public.quote_item_measurements.Owners can manage quote item measurements\",\"pol:public.quote_items.Owners can manage quote items\",\"pol:public.quote_sections.Owners can manage quote sections\",\"pol:public.quote_storage_gc.Owners ack own storage gc\",\"pol:public.quote_storage_gc.Owners read own storage gc\",\"pol:public.quotecode_documents.Allow public insert/select\",\"pol:public.quotecode_documents.Owners can manage documents\",\"pol:public.quotecode_documents.Public can view documents\",\"pol:public.quotes.Owners can manage quotes\",\"pol:public.services.Owners can manage services\",\"pol:storage.objects.Authenticated owners upload quote files\",\"pol:storage.objects.Owners delete own quote files\",\"pol:storage.objects.Owners read own quote files\",\"rel:auth.amr_id_pk:i\",\"rel:auth.audit_log_entries:r\",\"rel:auth.audit_log_entries_pkey:i\",\"rel:auth.audit_logs_instance_id_idx:i\",\"rel:auth.confirmation_token_idx:i\",\"rel:auth.custom_oauth_providers:r\",\"rel:auth.custom_oauth_providers_created_at_idx:i\",\"rel:auth.custom_oauth_providers_enabled_idx:i\",\"rel:auth.custom_oauth_providers_identifier_idx:i\",\"rel:auth.custom_oauth_providers_identifier_key:i\",\"rel:auth.custom_oauth_providers_pkey:i\",\"rel:auth.custom_oauth_providers_provider_type_idx:i\",\"rel:auth.email_change_token_current_idx:i\",\"rel:auth.email_change_token_new_idx:i\",\"rel:auth.factor_id_created_at_idx:i\",\"rel:auth.flow_state:r\",\"rel:auth.flow_state_created_at_idx:i\",\"rel:auth.flow_state_pkey:i\",\"rel:auth.identities:r\",\"rel:auth.identities_email_idx:i\",\"rel:auth.identities_pkey:i\",\"rel:auth.identities_provider_id_provider_unique:i\",\"rel:auth.identities_user_id_idx:i\",\"rel:auth.idx_auth_code:i\",\"rel:auth.idx_oauth_client_states_created_at:i\",\"rel:auth.idx_user_id_auth_method:i\",\"rel:auth.idx_users_created_at_desc:i\",\"rel:auth.idx_users_email:i\",\"rel:auth.idx_users_last_sign_in_at_desc:i\",\"rel:auth.idx_users_name:i\",\"rel:auth.instances:r\",\"rel:auth.instances_pkey:i\",\"rel:auth.mfa_amr_claims:r\",\"rel:auth.mfa_amr_claims_session_id_authentication_method_pkey:i\",\"rel:auth.mfa_challenge_created_at_idx:i\",\"rel:auth.mfa_challenges:r\",\"rel:auth.mfa_challenges_pkey:i\",\"rel:auth.mfa_factors:r\",\"rel:auth.mfa_factors_last_challenged_at_key:i\",\"rel:auth.mfa_factors_pkey:i\",\"rel:auth.mfa_factors_user_friendly_name_unique:i\",\"rel:auth.mfa_factors_user_id_idx:i\",\"rel:auth.mfa_recovery_code_sets:r\",\"rel:auth.mfa_recovery_code_sets_mfa_factor_id_key:i\",\"rel:auth.mfa_recovery_code_sets_pkey:i\",\"rel:auth.mfa_recovery_code_sets_user_id_key:i\",\"rel:auth.mfa_recovery_codes:r\",\"rel:auth.mfa_recovery_codes_pkey:i\",\"rel:auth.mfa_recovery_codes_set_id_idx:i\",\"rel:auth.oauth_auth_pending_exp_idx:i\",\"rel:auth.oauth_authorizations:r\",\"rel:auth.oauth_authorizations_authorization_code_key:i\",\"rel:auth.oauth_authorizations_authorization_id_key:i\",\"rel:auth.oauth_authorizations_pkey:i\",\"rel:auth.oauth_client_states:r\",\"rel:auth.oauth_client_states_pkey:i\",\"rel:auth.oauth_clients:r\",\"rel:auth.oauth_clients_deleted_at_idx:i\",\"rel:auth.oauth_clients_pkey:i\",\"rel:auth.oauth_consents:r\",\"rel:auth.oauth_consents_active_client_idx:i\",\"rel:auth.oauth_consents_active_user_client_idx:i\",\"rel:auth.oauth_consents_pkey:i\",\"rel:auth.oauth_consents_user_client_unique:i\",\"rel:auth.oauth_consents_user_order_idx:i\",\"rel:auth.one_time_tokens:r\",\"rel:auth.one_time_tokens_pkey:i\",\"rel:auth.one_time_tokens_relates_to_hash_idx:i\",\"rel:auth.one_time_tokens_token_hash_hash_idx:i\",\"rel:auth.one_time_tokens_user_id_token_type_key:i\",\"rel:auth.reauthentication_token_idx:i\",\"rel:auth.recovery_token_idx:i\",\"rel:auth.refresh_tokens:r\",\"rel:auth.refresh_tokens_id_seq:S\",\"rel:auth.refresh_tokens_instance_id_idx:i\",\"rel:auth.refresh_tokens_instance_id_user_id_idx:i\",\"rel:auth.refresh_tokens_parent_idx:i\",\"rel:auth.refresh_tokens_pkey:i\",\"rel:auth.refresh_tokens_session_id_revoked_idx:i\",\"rel:auth.refresh_tokens_token_unique:i\",\"rel:auth.refresh_tokens_updated_at_idx:i\",\"rel:auth.saml_providers:r\",\"rel:auth.saml_providers_entity_id_key:i\",\"rel:auth.saml_providers_pkey:i\",\"rel:auth.saml_providers_sso_provider_id_idx:i\",\"rel:auth.saml_relay_states:r\",\"rel:auth.saml_relay_states_created_at_idx:i\",\"rel:auth.saml_relay_states_for_email_idx:i\",\"rel:auth.saml_relay_states_pkey:i\",\"rel:auth.saml_relay_states_sso_provider_id_idx:i\",\"rel:auth.schema_migrations:r\",\"rel:auth.schema_migrations_pkey:i\",\"rel:auth.scim_tokens:r\",\"rel:auth.scim_tokens_expires_at_idx:i\",\"rel:auth.scim_tokens_pkey:i\",\"rel:auth.scim_tokens_revoked_at_idx:i\",\"rel:auth.scim_tokens_sso_provider_id_idx:i\",\"rel:auth.scim_tokens_token_hash_key:i\",\"rel:auth.scim_users:r\",\"rel:auth.scim_users_created_at_idx:i\",\"rel:auth.scim_users_deleted_at_idx:i\",\"rel:auth.scim_users_external_id_key:i\",\"rel:auth.scim_users_id_idx:i\",\"rel:auth.scim_users_pkey:i\",\"rel:auth.scim_users_sso_provider_id_idx:i\",\"rel:auth.scim_users_updated_at_idx:i\",\"rel:auth.scim_users_user_id_idx:i\",\"rel:auth.scim_users_user_name_idx:i\",\"rel:auth.scim_users_user_name_key:i\",\"rel:auth.sessions:r\",\"rel:auth.sessions_not_after_idx:i\",\"rel:auth.sessions_oauth_client_id_idx:i\",\"rel:auth.sessions_pkey:i\",\"rel:auth.sessions_user_id_idx:i\",\"rel:auth.sso_domains:r\",\"rel:auth.sso_domains_domain_idx:i\",\"rel:auth.sso_domains_pkey:i\",\"rel:auth.sso_domains_sso_provider_id_idx:i\",\"rel:auth.sso_providers:r\",\"rel:auth.sso_providers_pkey:i\",\"rel:auth.sso_providers_resource_id_idx:i\",\"rel:auth.sso_providers_resource_id_pattern_idx:i\",\"rel:auth.unique_phone_factor_per_user:i\",\"rel:auth.user_id_created_at_idx:i\",\"rel:auth.users:r\",\"rel:auth.users_email_partial_key:i\",\"rel:auth.users_instance_id_email_idx:i\",\"rel:auth.users_instance_id_idx:i\",\"rel:auth.users_is_anonymous_idx:i\",\"rel:auth.users_phone_key:i\",\"rel:auth.users_pkey:i\",\"rel:auth.webauthn_challenges:r\",\"rel:auth.webauthn_challenges_expires_at_idx:i\",\"rel:auth.webauthn_challenges_pkey:i\",\"rel:auth.webauthn_challenges_user_id_idx:i\",\"rel:auth.webauthn_credentials:r\",\"rel:auth.webauthn_credentials_credential_id_key:i\",\"rel:auth.webauthn_credentials_pkey:i\",\"rel:auth.webauthn_credentials_user_id_idx:i\",\"rel:public.business_quote_sequences:r\",\"rel:public.business_quote_sequences_pkey:i\",\"rel:public.business_settings:r\",\"rel:public.business_settings_id_seq:S\",\"rel:public.business_settings_pkey:i\",\"rel:public.business_settings_user_id_idx:i\",\"rel:public.business_settings_user_id_unique:i\",\"rel:public.chat_logs:r\",\"rel:public.chat_logs_pkey:i\",\"rel:public.clients:r\",\"rel:public.clients_pkey:i\",\"rel:public.expenses:r\",\"rel:public.expenses_pkey:i\",\"rel:public.quote_attachments:r\",\"rel:public.quote_attachments_pkey:i\",\"rel:public.quote_item_measurements:r\",\"rel:public.quote_item_measurements_pkey:i\",\"rel:public.quote_items:r\",\"rel:public.quote_items_id_quote_id_key:i\",\"rel:public.quote_items_pkey:i\",\"rel:public.quote_sections:r\",\"rel:public.quote_sections_id_quote_id_key:i\",\"rel:public.quote_sections_pkey:i\",\"rel:public.quote_storage_gc:r\",\"rel:public.quote_storage_gc_bucket_id_storage_path_key:i\",\"rel:public.quote_storage_gc_id_seq:S\",\"rel:public.quote_storage_gc_pkey:i\",\"rel:public.quotecode_documents:r\",\"rel:public.quotecode_documents_pkey:i\",\"rel:public.quotes:r\",\"rel:public.quotes_pkey:i\",\"rel:public.quotes_quote_number_seq:S\",\"rel:public.quotes_user_quote_number_unique:i\",\"rel:public.services:r\",\"rel:public.services_id_seq:S\",\"rel:public.services_pkey:i\",\"rel:public.trial_reminder_deliveries:r\",\"rel:public.trial_reminder_deliveries_pkey:i\",\"rel:storage.bname:i\",\"rel:storage.buckets:r\",\"rel:storage.buckets_analytics:r\",\"rel:storage.buckets_analytics_pkey:i\",\"rel:storage.buckets_analytics_unique_name_idx:i\",\"rel:storage.buckets_pkey:i\",\"rel:storage.buckets_vectors:r\",\"rel:storage.buckets_vectors_pkey:i\",\"rel:storage.idx_multipart_uploads_list:i\",\"rel:storage.idx_objects_bucket_id_name:i\",\"rel:storage.idx_objects_bucket_id_name_lower:i\",\"rel:storage.idx_objects_current_version:i\",\"rel:storage.idx_objects_delete_markers:i\",\"rel:storage.idx_objects_null_version:i\",\"rel:storage.migrations:r\",\"rel:storage.migrations_name_key:i\",\"rel:storage.migrations_pkey:i\",\"rel:storage.name_prefix_search:i\",\"rel:storage.objects:r\",\"rel:storage.objects_bucket_id_name_version_key:i\",\"rel:storage.objects_pkey:i\",\"rel:storage.s3_multipart_uploads:r\",\"rel:storage.s3_multipart_uploads_parts:r\",\"rel:storage.s3_multipart_uploads_parts_pkey:i\",\"rel:storage.s3_multipart_uploads_pkey:i\",\"rel:storage.vector_indexes:r\",\"rel:storage.vector_indexes_name_bucket_id_idx:i\",\"rel:storage.vector_indexes_pkey:i\",\"trg:auth.users.on_auth_user_created_migration\",\"trg:public.business_settings.guard_business_settings_plan_trial_update\",\"trg:public.quote_attachments.enqueue_quote_attachment_gc\",\"trg:public.quote_attachments.guard_quote_attachments_immutability\",\"trg:public.quote_item_measurements.guard_quote_item_measurements_immutability\",\"trg:public.quote_items.guard_quote_items_immutability\",\"trg:public.quote_sections.guard_quote_sections_immutability\",\"trg:public.quote_sections.unsection_quote_items_before_section_delete\",\"trg:public.quotes.guard_quote_immutability_delete_trigger\",\"trg:public.quotes.guard_quote_immutability_update\",\"trg:public.quotes.quotes_protect_quote_number\",\"trg:storage.buckets.enforce_bucket_name_length_trigger\",\"trg:storage.buckets.protect_bucket_control_insert\",\"trg:storage.buckets.protect_bucket_control_update\",\"trg:storage.buckets.protect_bucket_control_update_role\",\"trg:storage.buckets.protect_buckets_delete\",\"trg:storage.objects.protect_objects_delete\",\"trg:storage.objects.update_objects_updated_at\"],\"publicFunctionDefsSha256\":\"adb63fd4efa30adae6d64729e9d12a81e46063b222946ebd64c8fcfcfddce56a\",\"publicColumnsSha256\":\"e6c4406ac5921b19c29bba918f5c83200a938ba533fbc7da8d24354492472ded\",\"publicTableAclSha256\":\"d14da1d6ef5d0cb72ee7909fe17cc253b45fad59e857b1980676991f732ae6ce\"}'::jsonb THEN RAISE EXCEPTION 'TK_PRESTATE_DRIFT: the snapshot changed since the pre-state capture'; END IF;",
  "END",
  "$tk_guard$;",
  "-- ===== 20260929000000_drop_legacy_approve_quote_public.sql (verbatim; sha256 7c9c1fb54e7ce99896b9ba49f17b0608c686c340faa65ecefbb78ef949929ef4) =====",
  "-- 20260929000000_drop_legacy_approve_quote_public.sql",
  "--",
  "-- SECURITY FIX (Owner decision after independent Codex review, 2026-09-28: remediation APPROVED FOR PREPARATION).",
  "-- Drops EXACTLY public.approve_quote_public(uuid) and public.approve_quote_public(uuid, text): legacy, pre-git,",
  "-- Production-native SECURITY DEFINER functions with no authorization / state / expiry / signature checks, EXECUTE held by",
  "-- PUBLIC, anon and authenticated (fresh read-only probe 2026-09-28T20:51Z). No frontend, Edge Function, database object or",
  "-- migration calls them. The supported approval RPC public.public_approve_quote(uuid, text) (OD-9 + OD-1, migration",
  "-- 20260922000000) is NOT modified - its definition hash and ACL are asserted unchanged before and after.",
  "--",
  "-- Execution contract:",
  "--   - Applied ONLY through the governed migration path (one-migration executor profile): the executor owns the transaction",
  "--     (BEGIN / COMMIT) and inserts the ledger row. This file contains no BEGIN / COMMIT / ROLLBACK and no ledger insert.",
  "--   - Idempotent across environments: on TEST (the two functions never existed) every check passes and both DROPs are",
  "--     no-ops; on Production both are dropped. A replay after success is a no-op as well (the executor refuses replays).",
  "--   - RESTRICT only (never CASCADE). No GRANT / REVOKE on any other object.",
  "--   - FORWARD-FIX ONLY: there is no rollback that recreates the vulnerable functions. The draft rollback script kept in the",
  "--     review evidence package (p0/aqp/draft-rollback-restore-legacy-approve_quote_public.sql) is NEVER APPLY - historical",
  "--     review material only; it must never be executed against any environment.",
  "--   - Every catalog / function reference is schema-qualified and search_path is pinned to pg_catalog, pg_temp for this",
  "--     transaction.",
  "--",
  "-- Refusal codes (all abort the executor's transaction, nothing is changed):",
  "--   TKA00 TK_AQP_SEARCH_PATH              search_path is not exactly the pinned 'pg_catalog, pg_temp' (SET LOCAL not in effect)",
  "--   TKA01 TK_AQP_UNEXPECTED_OVERLOAD      an approve_quote_public overload other than the two known signatures exists",
  "--   TKA02 TK_AQP_UNEXPECTED_DEFINITION    a known overload exists but its definition differs from the probed vulnerable body",
  "--   TKA03 TK_AQP_DEPENDENCY               an object depends on one of the overloads (normal / auto pg_depend, a trigger /",
  "--                                         event trigger), or any OTHER routine body / policy / rule / trigger text names it",
  "--   TKA04 TK_AQP_CANONICAL_MISSING        public.public_approve_quote(uuid, text) does not exist",
  "--   TKA05 TK_AQP_CANONICAL_DEFINITION     public.public_approve_quote definition hash differs from the expected constant",
  "--   TKA06 TK_AQP_CANONICAL_ACL            public.public_approve_quote ACL / owner differs from the expected constant",
  "--   TKA07 TK_AQP_POST_STILL_PRESENT       an approve_quote_public overload still exists after the DROP",
  "--",
  "-- Expected constants (provenance: p0/aqp-fix/EXPECTED_CONSTANTS.md; fresh probes security-probe-aqp-PRODUCTION-",
  "-- 20260928T205133Z.json and security-probe-aqp-TEST-20260928T205140Z.json, equal on both environments where applicable):",
  "--   public_approve_quote(uuid, text) definition sha256 = eab641c566ec6776c0f3a389e6ba80d7e7f204d1479194f681ca51e838aeb855",
  "--   public_approve_quote(uuid, text) ACL (aclitems sorted, COLLATE \"C\") = anon=X/postgres,authenticated=X/postgres,postgres=X/postgres",
  "--   public_approve_quote(uuid, text) owner = postgres",
  "--   approve_quote_public(uuid)       definition sha256 = b50d1c880ba4f260eeea7925c33ca49d1d2dbed76730b4ba69f3b7af2b0a9a31",
  "--   approve_quote_public(uuid, text) definition sha256 = e36067ab64ff0c8d52a5eb200e175565a160ba3cac1880b6924573197cf17d7b",
  "--   (definition sha256 = sha256(convert_to(pg_get_functiondef(oid), 'UTF8')), exactly as the probe computed it)",
  "",
  "SET LOCAL search_path = pg_catalog, pg_temp;",
  "",
  "DO $tk_aqp_pre$",
  "DECLARE",
  "  c_canonical_sha  constant text := 'eab641c566ec6776c0f3a389e6ba80d7e7f204d1479194f681ca51e838aeb855';",
  "  c_canonical_acl  constant text := 'anon=X/postgres,authenticated=X/postgres,postgres=X/postgres';",
  "  c_canonical_own  constant text := 'postgres';",
  "  c_legacy1_sha    constant text := 'b50d1c880ba4f260eeea7925c33ca49d1d2dbed76730b4ba69f3b7af2b0a9a31';",
  "  c_legacy2_sha    constant text := 'e36067ab64ff0c8d52a5eb200e175565a160ba3cac1880b6924573197cf17d7b';",
  "  v_legacy1        oid := pg_catalog.to_regprocedure('public.approve_quote_public(uuid)')::oid;",
  "  v_legacy2        oid := pg_catalog.to_regprocedure('public.approve_quote_public(uuid,text)')::oid;",
  "  v_canonical      oid := pg_catalog.to_regprocedure('public.public_approve_quote(uuid,text)')::oid;",
  "  v_legacy         oid[];",
  "  v_n              bigint;",
  "  v_sha            text;",
  "  v_acl            text;",
  "  v_owner          text;",
  "BEGIN",
  "  -- TKA00: prove the pinned search_path (SET LOCAL above) is in effect inside the executor's transaction.",
  "  IF pg_catalog.current_setting('search_path') COLLATE pg_catalog.\"C\" IS DISTINCT FROM 'pg_catalog, pg_temp' COLLATE pg_catalog.\"C\" THEN",
  "    RAISE EXCEPTION 'TK_AQP_SEARCH_PATH: search_path is [%], expected [pg_catalog, pg_temp] - SET LOCAL not in effect (not inside the executor transaction?)',",
  "      pg_catalog.current_setting('search_path') USING ERRCODE = 'TKA00';",
  "  END IF;",
  "",
  "  -- TKA01: third-overload refusal (0, 1 or 2 of the two known signatures are allowed; anything else is not).",
  "  SELECT pg_catalog.count(*) INTO v_n",
  "    FROM pg_catalog.pg_proc p",
  "    JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace",
  "   WHERE n.nspname = 'public' AND p.proname = 'approve_quote_public'",
  "     AND p.oid IS DISTINCT FROM v_legacy1 AND p.oid IS DISTINCT FROM v_legacy2;",
  "  IF v_n <> 0 THEN",
  "    RAISE EXCEPTION 'TK_AQP_UNEXPECTED_OVERLOAD: % unexpected public.approve_quote_public overload(s) exist', v_n USING ERRCODE = 'TKA01';",
  "  END IF;",
  "",
  "  -- TKA02: the known overloads, when present, must be exactly the probed vulnerable bodies (anything else = re-assess).",
  "  IF v_legacy1 IS NOT NULL THEN",
  "    v_sha := pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(pg_catalog.pg_get_functiondef(v_legacy1), 'UTF8')), 'hex');",
  "    IF v_sha IS DISTINCT FROM c_legacy1_sha THEN",
  "      RAISE EXCEPTION 'TK_AQP_UNEXPECTED_DEFINITION: public.approve_quote_public(uuid) definition sha256 % differs from the probed %', v_sha, c_legacy1_sha USING ERRCODE = 'TKA02';",
  "    END IF;",
  "  END IF;",
  "  IF v_legacy2 IS NOT NULL THEN",
  "    v_sha := pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(pg_catalog.pg_get_functiondef(v_legacy2), 'UTF8')), 'hex');",
  "    IF v_sha IS DISTINCT FROM c_legacy2_sha THEN",
  "      RAISE EXCEPTION 'TK_AQP_UNEXPECTED_DEFINITION: public.approve_quote_public(uuid, text) definition sha256 % differs from the probed %', v_sha, c_legacy2_sha USING ERRCODE = 'TKA02';",
  "    END IF;",
  "  END IF;",
  "",
  "  -- TKA03: dependency refusal. Any normal ('n') or auto ('a') dependency ON either overload (views, SQL-body functions,",
  "  -- policies, triggers, rewrite rules, event triggers, column defaults ...) refuses; role/default-ACL links live in",
  "  -- pg_shdepend and are dropped with the function. Triggers are also checked directly.",
  "  v_legacy := pg_catalog.array_remove(ARRAY[v_legacy1, v_legacy2], NULL::oid);",
  "  IF pg_catalog.cardinality(v_legacy) > 0 THEN",
  "    SELECT pg_catalog.count(*) INTO v_n",
  "      FROM pg_catalog.pg_depend d",
  "     WHERE d.refclassid = 'pg_catalog.pg_proc'::pg_catalog.regclass",
  "       AND d.refobjid = ANY (v_legacy)",
  "       AND d.deptype IN ('n', 'a');",
  "    IF v_n <> 0 THEN",
  "      RAISE EXCEPTION 'TK_AQP_DEPENDENCY: % object(s) depend on public.approve_quote_public - refusing (no CASCADE)', v_n USING ERRCODE = 'TKA03';",
  "    END IF;",
  "    SELECT pg_catalog.count(*) INTO v_n FROM pg_catalog.pg_trigger t WHERE t.tgfoid = ANY (v_legacy);",
  "    IF v_n <> 0 THEN",
  "      RAISE EXCEPTION 'TK_AQP_DEPENDENCY: % trigger(s) call public.approve_quote_public - refusing', v_n USING ERRCODE = 'TKA03';",
  "    END IF;",
  "    SELECT pg_catalog.count(*) INTO v_n FROM pg_catalog.pg_event_trigger e WHERE e.evtfoid = ANY (v_legacy);",
  "    IF v_n <> 0 THEN",
  "      RAISE EXCEPTION 'TK_AQP_DEPENDENCY: % event trigger(s) call public.approve_quote_public - refusing', v_n USING ERRCODE = 'TKA03';",
  "    END IF;",
  "  END IF;",
  "",
  "  -- TKA03 (text references, checked whether or not the overloads exist): PL/pgSQL and other non-SQL-body routines are",
  "  -- invisible to pg_depend, so ANY other routine (any schema, prokind f/p) whose source names approve_quote_public refuses;",
  "  -- likewise any policy expression, rewrite rule, or trigger definition / arguments text. The canonical",
  "  -- public.public_approve_quote body does not contain the substring (verified in both probe JSONs).",
  "  SELECT pg_catalog.count(*) INTO v_n",
  "    FROM pg_catalog.pg_proc p",
  "   WHERE p.prokind IN ('f', 'p')",
  "     AND p.oid IS DISTINCT FROM v_legacy1 AND p.oid IS DISTINCT FROM v_legacy2",
  "     AND pg_catalog.strpos(COALESCE(p.prosrc, '') COLLATE pg_catalog.\"C\", 'approve_quote_public' COLLATE pg_catalog.\"C\") > 0;",
  "  IF v_n <> 0 THEN",
  "    RAISE EXCEPTION 'TK_AQP_DEPENDENCY: % other routine(s) reference approve_quote_public in their source - refusing', v_n USING ERRCODE = 'TKA03';",
  "  END IF;",
  "  SELECT pg_catalog.count(*) INTO v_n",
  "    FROM pg_catalog.pg_policy pol",
  "   WHERE pg_catalog.strpos((COALESCE(pg_catalog.pg_get_expr(pol.polqual, pol.polrelid), '') || ' ' ||",
  "                            COALESCE(pg_catalog.pg_get_expr(pol.polwithcheck, pol.polrelid), '')) COLLATE pg_catalog.\"C\",",
  "                           'approve_quote_public' COLLATE pg_catalog.\"C\") > 0;",
  "  IF v_n <> 0 THEN",
  "    RAISE EXCEPTION 'TK_AQP_DEPENDENCY: % policy expression(s) reference approve_quote_public - refusing', v_n USING ERRCODE = 'TKA03';",
  "  END IF;",
  "  SELECT pg_catalog.count(*) INTO v_n",
  "    FROM pg_catalog.pg_rewrite r",
  "   WHERE pg_catalog.strpos(COALESCE(pg_catalog.pg_get_ruledef(r.oid), '') COLLATE pg_catalog.\"C\", 'approve_quote_public' COLLATE pg_catalog.\"C\") > 0;",
  "  IF v_n <> 0 THEN",
  "    RAISE EXCEPTION 'TK_AQP_DEPENDENCY: % rewrite rule(s) / view(s) reference approve_quote_public - refusing', v_n USING ERRCODE = 'TKA03';",
  "  END IF;",
  "  SELECT pg_catalog.count(*) INTO v_n",
  "    FROM pg_catalog.pg_trigger t",
  "   WHERE NOT t.tgisinternal",
  "     AND pg_catalog.strpos((pg_catalog.pg_get_triggerdef(t.oid) || ' ' || pg_catalog.encode(t.tgargs, 'escape')) COLLATE pg_catalog.\"C\",",
  "                           'approve_quote_public' COLLATE pg_catalog.\"C\") > 0;",
  "  IF v_n <> 0 THEN",
  "    RAISE EXCEPTION 'TK_AQP_DEPENDENCY: % trigger definition(s) / argument list(s) reference approve_quote_public - refusing', v_n USING ERRCODE = 'TKA03';",
  "  END IF;",
  "",
  "  -- TKA04..TKA06: the canonical approval RPC must exist, byte-identical in definition, with the canonical ACL and owner.",
  "  IF v_canonical IS NULL THEN",
  "    RAISE EXCEPTION 'TK_AQP_CANONICAL_MISSING: public.public_approve_quote(uuid, text) does not exist' USING ERRCODE = 'TKA04';",
  "  END IF;",
  "  v_sha := pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(pg_catalog.pg_get_functiondef(v_canonical), 'UTF8')), 'hex');",
  "  IF v_sha IS DISTINCT FROM c_canonical_sha THEN",
  "    RAISE EXCEPTION 'TK_AQP_CANONICAL_DEFINITION: public.public_approve_quote definition sha256 % != expected %', v_sha, c_canonical_sha USING ERRCODE = 'TKA05';",
  "  END IF;",
  "  SELECT (SELECT pg_catalog.string_agg(a::pg_catalog.text, ',' ORDER BY a::pg_catalog.text COLLATE pg_catalog.\"C\") FROM pg_catalog.unnest(p.proacl) AS a),",
  "         pg_catalog.pg_get_userbyid(p.proowner)::pg_catalog.text",
  "    INTO v_acl, v_owner",
  "    FROM pg_catalog.pg_proc p WHERE p.oid = v_canonical;",
  "  IF v_acl IS DISTINCT FROM c_canonical_acl OR v_owner IS DISTINCT FROM c_canonical_own THEN",
  "    RAISE EXCEPTION 'TK_AQP_CANONICAL_ACL: public.public_approve_quote ACL [%] owner [%] != expected [%] [%]', v_acl, v_owner, c_canonical_acl, c_canonical_own USING ERRCODE = 'TKA06';",
  "  END IF;",
  "END",
  "$tk_aqp_pre$;",
  "",
  "DROP FUNCTION IF EXISTS public.approve_quote_public(uuid) RESTRICT;",
  "DROP FUNCTION IF EXISTS public.approve_quote_public(uuid, text) RESTRICT;",
  "",
  "DO $tk_aqp_post$",
  "DECLARE",
  "  c_canonical_sha  constant text := 'eab641c566ec6776c0f3a389e6ba80d7e7f204d1479194f681ca51e838aeb855';",
  "  c_canonical_acl  constant text := 'anon=X/postgres,authenticated=X/postgres,postgres=X/postgres';",
  "  c_canonical_own  constant text := 'postgres';",
  "  v_canonical      oid := pg_catalog.to_regprocedure('public.public_approve_quote(uuid,text)')::oid;",
  "  v_n              bigint;",
  "  v_sha            text;",
  "  v_acl            text;",
  "  v_owner          text;",
  "BEGIN",
  "  SELECT pg_catalog.count(*) INTO v_n",
  "    FROM pg_catalog.pg_proc p",
  "    JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace",
  "   WHERE n.nspname = 'public' AND p.proname = 'approve_quote_public';",
  "  IF v_n <> 0 THEN",
  "    RAISE EXCEPTION 'TK_AQP_POST_STILL_PRESENT: % public.approve_quote_public overload(s) remain', v_n USING ERRCODE = 'TKA07';",
  "  END IF;",
  "  IF v_canonical IS NULL THEN",
  "    RAISE EXCEPTION 'TK_AQP_CANONICAL_MISSING: public.public_approve_quote(uuid, text) disappeared' USING ERRCODE = 'TKA04';",
  "  END IF;",
  "  v_sha := pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(pg_catalog.pg_get_functiondef(v_canonical), 'UTF8')), 'hex');",
  "  IF v_sha IS DISTINCT FROM c_canonical_sha THEN",
  "    RAISE EXCEPTION 'TK_AQP_CANONICAL_DEFINITION: public.public_approve_quote definition changed (sha256 %)', v_sha USING ERRCODE = 'TKA05';",
  "  END IF;",
  "  SELECT (SELECT pg_catalog.string_agg(a::pg_catalog.text, ',' ORDER BY a::pg_catalog.text COLLATE pg_catalog.\"C\") FROM pg_catalog.unnest(p.proacl) AS a),",
  "         pg_catalog.pg_get_userbyid(p.proowner)::pg_catalog.text",
  "    INTO v_acl, v_owner",
  "    FROM pg_catalog.pg_proc p WHERE p.oid = v_canonical;",
  "  IF v_acl IS DISTINCT FROM c_canonical_acl OR v_owner IS DISTINCT FROM c_canonical_own THEN",
  "    RAISE EXCEPTION 'TK_AQP_CANONICAL_ACL: public.public_approve_quote ACL [%] owner [%] changed', v_acl, v_owner USING ERRCODE = 'TKA06';",
  "  END IF;",
  "END",
  "$tk_aqp_post$;",
  "",
  "-- ===== ledger row: same transaction as the schema change =====",
  "INSERT INTO supabase_migrations.schema_migrations (version, name, statements) VALUES ('20260929000000', 'drop_legacy_approve_quote_public', ARRAY[$tk_stmt_7c9c1fb54e7c_47a45349bc76$-- 20260929000000_drop_legacy_approve_quote_public.sql",
  "--",
  "-- SECURITY FIX (Owner decision after independent Codex review, 2026-09-28: remediation APPROVED FOR PREPARATION).",
  "-- Drops EXACTLY public.approve_quote_public(uuid) and public.approve_quote_public(uuid, text): legacy, pre-git,",
  "-- Production-native SECURITY DEFINER functions with no authorization / state / expiry / signature checks, EXECUTE held by",
  "-- PUBLIC, anon and authenticated (fresh read-only probe 2026-09-28T20:51Z). No frontend, Edge Function, database object or",
  "-- migration calls them. The supported approval RPC public.public_approve_quote(uuid, text) (OD-9 + OD-1, migration",
  "-- 20260922000000) is NOT modified - its definition hash and ACL are asserted unchanged before and after.",
  "--",
  "-- Execution contract:",
  "--   - Applied ONLY through the governed migration path (one-migration executor profile): the executor owns the transaction",
  "--     (BEGIN / COMMIT) and inserts the ledger row. This file contains no BEGIN / COMMIT / ROLLBACK and no ledger insert.",
  "--   - Idempotent across environments: on TEST (the two functions never existed) every check passes and both DROPs are",
  "--     no-ops; on Production both are dropped. A replay after success is a no-op as well (the executor refuses replays).",
  "--   - RESTRICT only (never CASCADE). No GRANT / REVOKE on any other object.",
  "--   - FORWARD-FIX ONLY: there is no rollback that recreates the vulnerable functions. The draft rollback script kept in the",
  "--     review evidence package (p0/aqp/draft-rollback-restore-legacy-approve_quote_public.sql) is NEVER APPLY - historical",
  "--     review material only; it must never be executed against any environment.",
  "--   - Every catalog / function reference is schema-qualified and search_path is pinned to pg_catalog, pg_temp for this",
  "--     transaction.",
  "--",
  "-- Refusal codes (all abort the executor's transaction, nothing is changed):",
  "--   TKA00 TK_AQP_SEARCH_PATH              search_path is not exactly the pinned 'pg_catalog, pg_temp' (SET LOCAL not in effect)",
  "--   TKA01 TK_AQP_UNEXPECTED_OVERLOAD      an approve_quote_public overload other than the two known signatures exists",
  "--   TKA02 TK_AQP_UNEXPECTED_DEFINITION    a known overload exists but its definition differs from the probed vulnerable body",
  "--   TKA03 TK_AQP_DEPENDENCY               an object depends on one of the overloads (normal / auto pg_depend, a trigger /",
  "--                                         event trigger), or any OTHER routine body / policy / rule / trigger text names it",
  "--   TKA04 TK_AQP_CANONICAL_MISSING        public.public_approve_quote(uuid, text) does not exist",
  "--   TKA05 TK_AQP_CANONICAL_DEFINITION     public.public_approve_quote definition hash differs from the expected constant",
  "--   TKA06 TK_AQP_CANONICAL_ACL            public.public_approve_quote ACL / owner differs from the expected constant",
  "--   TKA07 TK_AQP_POST_STILL_PRESENT       an approve_quote_public overload still exists after the DROP",
  "--",
  "-- Expected constants (provenance: p0/aqp-fix/EXPECTED_CONSTANTS.md; fresh probes security-probe-aqp-PRODUCTION-",
  "-- 20260928T205133Z.json and security-probe-aqp-TEST-20260928T205140Z.json, equal on both environments where applicable):",
  "--   public_approve_quote(uuid, text) definition sha256 = eab641c566ec6776c0f3a389e6ba80d7e7f204d1479194f681ca51e838aeb855",
  "--   public_approve_quote(uuid, text) ACL (aclitems sorted, COLLATE \"C\") = anon=X/postgres,authenticated=X/postgres,postgres=X/postgres",
  "--   public_approve_quote(uuid, text) owner = postgres",
  "--   approve_quote_public(uuid)       definition sha256 = b50d1c880ba4f260eeea7925c33ca49d1d2dbed76730b4ba69f3b7af2b0a9a31",
  "--   approve_quote_public(uuid, text) definition sha256 = e36067ab64ff0c8d52a5eb200e175565a160ba3cac1880b6924573197cf17d7b",
  "--   (definition sha256 = sha256(convert_to(pg_get_functiondef(oid), 'UTF8')), exactly as the probe computed it)",
  "",
  "SET LOCAL search_path = pg_catalog, pg_temp;",
  "",
  "DO $tk_aqp_pre$",
  "DECLARE",
  "  c_canonical_sha  constant text := 'eab641c566ec6776c0f3a389e6ba80d7e7f204d1479194f681ca51e838aeb855';",
  "  c_canonical_acl  constant text := 'anon=X/postgres,authenticated=X/postgres,postgres=X/postgres';",
  "  c_canonical_own  constant text := 'postgres';",
  "  c_legacy1_sha    constant text := 'b50d1c880ba4f260eeea7925c33ca49d1d2dbed76730b4ba69f3b7af2b0a9a31';",
  "  c_legacy2_sha    constant text := 'e36067ab64ff0c8d52a5eb200e175565a160ba3cac1880b6924573197cf17d7b';",
  "  v_legacy1        oid := pg_catalog.to_regprocedure('public.approve_quote_public(uuid)')::oid;",
  "  v_legacy2        oid := pg_catalog.to_regprocedure('public.approve_quote_public(uuid,text)')::oid;",
  "  v_canonical      oid := pg_catalog.to_regprocedure('public.public_approve_quote(uuid,text)')::oid;",
  "  v_legacy         oid[];",
  "  v_n              bigint;",
  "  v_sha            text;",
  "  v_acl            text;",
  "  v_owner          text;",
  "BEGIN",
  "  -- TKA00: prove the pinned search_path (SET LOCAL above) is in effect inside the executor's transaction.",
  "  IF pg_catalog.current_setting('search_path') COLLATE pg_catalog.\"C\" IS DISTINCT FROM 'pg_catalog, pg_temp' COLLATE pg_catalog.\"C\" THEN",
  "    RAISE EXCEPTION 'TK_AQP_SEARCH_PATH: search_path is [%], expected [pg_catalog, pg_temp] - SET LOCAL not in effect (not inside the executor transaction?)',",
  "      pg_catalog.current_setting('search_path') USING ERRCODE = 'TKA00';",
  "  END IF;",
  "",
  "  -- TKA01: third-overload refusal (0, 1 or 2 of the two known signatures are allowed; anything else is not).",
  "  SELECT pg_catalog.count(*) INTO v_n",
  "    FROM pg_catalog.pg_proc p",
  "    JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace",
  "   WHERE n.nspname = 'public' AND p.proname = 'approve_quote_public'",
  "     AND p.oid IS DISTINCT FROM v_legacy1 AND p.oid IS DISTINCT FROM v_legacy2;",
  "  IF v_n <> 0 THEN",
  "    RAISE EXCEPTION 'TK_AQP_UNEXPECTED_OVERLOAD: % unexpected public.approve_quote_public overload(s) exist', v_n USING ERRCODE = 'TKA01';",
  "  END IF;",
  "",
  "  -- TKA02: the known overloads, when present, must be exactly the probed vulnerable bodies (anything else = re-assess).",
  "  IF v_legacy1 IS NOT NULL THEN",
  "    v_sha := pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(pg_catalog.pg_get_functiondef(v_legacy1), 'UTF8')), 'hex');",
  "    IF v_sha IS DISTINCT FROM c_legacy1_sha THEN",
  "      RAISE EXCEPTION 'TK_AQP_UNEXPECTED_DEFINITION: public.approve_quote_public(uuid) definition sha256 % differs from the probed %', v_sha, c_legacy1_sha USING ERRCODE = 'TKA02';",
  "    END IF;",
  "  END IF;",
  "  IF v_legacy2 IS NOT NULL THEN",
  "    v_sha := pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(pg_catalog.pg_get_functiondef(v_legacy2), 'UTF8')), 'hex');",
  "    IF v_sha IS DISTINCT FROM c_legacy2_sha THEN",
  "      RAISE EXCEPTION 'TK_AQP_UNEXPECTED_DEFINITION: public.approve_quote_public(uuid, text) definition sha256 % differs from the probed %', v_sha, c_legacy2_sha USING ERRCODE = 'TKA02';",
  "    END IF;",
  "  END IF;",
  "",
  "  -- TKA03: dependency refusal. Any normal ('n') or auto ('a') dependency ON either overload (views, SQL-body functions,",
  "  -- policies, triggers, rewrite rules, event triggers, column defaults ...) refuses; role/default-ACL links live in",
  "  -- pg_shdepend and are dropped with the function. Triggers are also checked directly.",
  "  v_legacy := pg_catalog.array_remove(ARRAY[v_legacy1, v_legacy2], NULL::oid);",
  "  IF pg_catalog.cardinality(v_legacy) > 0 THEN",
  "    SELECT pg_catalog.count(*) INTO v_n",
  "      FROM pg_catalog.pg_depend d",
  "     WHERE d.refclassid = 'pg_catalog.pg_proc'::pg_catalog.regclass",
  "       AND d.refobjid = ANY (v_legacy)",
  "       AND d.deptype IN ('n', 'a');",
  "    IF v_n <> 0 THEN",
  "      RAISE EXCEPTION 'TK_AQP_DEPENDENCY: % object(s) depend on public.approve_quote_public - refusing (no CASCADE)', v_n USING ERRCODE = 'TKA03';",
  "    END IF;",
  "    SELECT pg_catalog.count(*) INTO v_n FROM pg_catalog.pg_trigger t WHERE t.tgfoid = ANY (v_legacy);",
  "    IF v_n <> 0 THEN",
  "      RAISE EXCEPTION 'TK_AQP_DEPENDENCY: % trigger(s) call public.approve_quote_public - refusing', v_n USING ERRCODE = 'TKA03';",
  "    END IF;",
  "    SELECT pg_catalog.count(*) INTO v_n FROM pg_catalog.pg_event_trigger e WHERE e.evtfoid = ANY (v_legacy);",
  "    IF v_n <> 0 THEN",
  "      RAISE EXCEPTION 'TK_AQP_DEPENDENCY: % event trigger(s) call public.approve_quote_public - refusing', v_n USING ERRCODE = 'TKA03';",
  "    END IF;",
  "  END IF;",
  "",
  "  -- TKA03 (text references, checked whether or not the overloads exist): PL/pgSQL and other non-SQL-body routines are",
  "  -- invisible to pg_depend, so ANY other routine (any schema, prokind f/p) whose source names approve_quote_public refuses;",
  "  -- likewise any policy expression, rewrite rule, or trigger definition / arguments text. The canonical",
  "  -- public.public_approve_quote body does not contain the substring (verified in both probe JSONs).",
  "  SELECT pg_catalog.count(*) INTO v_n",
  "    FROM pg_catalog.pg_proc p",
  "   WHERE p.prokind IN ('f', 'p')",
  "     AND p.oid IS DISTINCT FROM v_legacy1 AND p.oid IS DISTINCT FROM v_legacy2",
  "     AND pg_catalog.strpos(COALESCE(p.prosrc, '') COLLATE pg_catalog.\"C\", 'approve_quote_public' COLLATE pg_catalog.\"C\") > 0;",
  "  IF v_n <> 0 THEN",
  "    RAISE EXCEPTION 'TK_AQP_DEPENDENCY: % other routine(s) reference approve_quote_public in their source - refusing', v_n USING ERRCODE = 'TKA03';",
  "  END IF;",
  "  SELECT pg_catalog.count(*) INTO v_n",
  "    FROM pg_catalog.pg_policy pol",
  "   WHERE pg_catalog.strpos((COALESCE(pg_catalog.pg_get_expr(pol.polqual, pol.polrelid), '') || ' ' ||",
  "                            COALESCE(pg_catalog.pg_get_expr(pol.polwithcheck, pol.polrelid), '')) COLLATE pg_catalog.\"C\",",
  "                           'approve_quote_public' COLLATE pg_catalog.\"C\") > 0;",
  "  IF v_n <> 0 THEN",
  "    RAISE EXCEPTION 'TK_AQP_DEPENDENCY: % policy expression(s) reference approve_quote_public - refusing', v_n USING ERRCODE = 'TKA03';",
  "  END IF;",
  "  SELECT pg_catalog.count(*) INTO v_n",
  "    FROM pg_catalog.pg_rewrite r",
  "   WHERE pg_catalog.strpos(COALESCE(pg_catalog.pg_get_ruledef(r.oid), '') COLLATE pg_catalog.\"C\", 'approve_quote_public' COLLATE pg_catalog.\"C\") > 0;",
  "  IF v_n <> 0 THEN",
  "    RAISE EXCEPTION 'TK_AQP_DEPENDENCY: % rewrite rule(s) / view(s) reference approve_quote_public - refusing', v_n USING ERRCODE = 'TKA03';",
  "  END IF;",
  "  SELECT pg_catalog.count(*) INTO v_n",
  "    FROM pg_catalog.pg_trigger t",
  "   WHERE NOT t.tgisinternal",
  "     AND pg_catalog.strpos((pg_catalog.pg_get_triggerdef(t.oid) || ' ' || pg_catalog.encode(t.tgargs, 'escape')) COLLATE pg_catalog.\"C\",",
  "                           'approve_quote_public' COLLATE pg_catalog.\"C\") > 0;",
  "  IF v_n <> 0 THEN",
  "    RAISE EXCEPTION 'TK_AQP_DEPENDENCY: % trigger definition(s) / argument list(s) reference approve_quote_public - refusing', v_n USING ERRCODE = 'TKA03';",
  "  END IF;",
  "",
  "  -- TKA04..TKA06: the canonical approval RPC must exist, byte-identical in definition, with the canonical ACL and owner.",
  "  IF v_canonical IS NULL THEN",
  "    RAISE EXCEPTION 'TK_AQP_CANONICAL_MISSING: public.public_approve_quote(uuid, text) does not exist' USING ERRCODE = 'TKA04';",
  "  END IF;",
  "  v_sha := pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(pg_catalog.pg_get_functiondef(v_canonical), 'UTF8')), 'hex');",
  "  IF v_sha IS DISTINCT FROM c_canonical_sha THEN",
  "    RAISE EXCEPTION 'TK_AQP_CANONICAL_DEFINITION: public.public_approve_quote definition sha256 % != expected %', v_sha, c_canonical_sha USING ERRCODE = 'TKA05';",
  "  END IF;",
  "  SELECT (SELECT pg_catalog.string_agg(a::pg_catalog.text, ',' ORDER BY a::pg_catalog.text COLLATE pg_catalog.\"C\") FROM pg_catalog.unnest(p.proacl) AS a),",
  "         pg_catalog.pg_get_userbyid(p.proowner)::pg_catalog.text",
  "    INTO v_acl, v_owner",
  "    FROM pg_catalog.pg_proc p WHERE p.oid = v_canonical;",
  "  IF v_acl IS DISTINCT FROM c_canonical_acl OR v_owner IS DISTINCT FROM c_canonical_own THEN",
  "    RAISE EXCEPTION 'TK_AQP_CANONICAL_ACL: public.public_approve_quote ACL [%] owner [%] != expected [%] [%]', v_acl, v_owner, c_canonical_acl, c_canonical_own USING ERRCODE = 'TKA06';",
  "  END IF;",
  "END",
  "$tk_aqp_pre$;",
  "",
  "DROP FUNCTION IF EXISTS public.approve_quote_public(uuid) RESTRICT;",
  "DROP FUNCTION IF EXISTS public.approve_quote_public(uuid, text) RESTRICT;",
  "",
  "DO $tk_aqp_post$",
  "DECLARE",
  "  c_canonical_sha  constant text := 'eab641c566ec6776c0f3a389e6ba80d7e7f204d1479194f681ca51e838aeb855';",
  "  c_canonical_acl  constant text := 'anon=X/postgres,authenticated=X/postgres,postgres=X/postgres';",
  "  c_canonical_own  constant text := 'postgres';",
  "  v_canonical      oid := pg_catalog.to_regprocedure('public.public_approve_quote(uuid,text)')::oid;",
  "  v_n              bigint;",
  "  v_sha            text;",
  "  v_acl            text;",
  "  v_owner          text;",
  "BEGIN",
  "  SELECT pg_catalog.count(*) INTO v_n",
  "    FROM pg_catalog.pg_proc p",
  "    JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace",
  "   WHERE n.nspname = 'public' AND p.proname = 'approve_quote_public';",
  "  IF v_n <> 0 THEN",
  "    RAISE EXCEPTION 'TK_AQP_POST_STILL_PRESENT: % public.approve_quote_public overload(s) remain', v_n USING ERRCODE = 'TKA07';",
  "  END IF;",
  "  IF v_canonical IS NULL THEN",
  "    RAISE EXCEPTION 'TK_AQP_CANONICAL_MISSING: public.public_approve_quote(uuid, text) disappeared' USING ERRCODE = 'TKA04';",
  "  END IF;",
  "  v_sha := pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(pg_catalog.pg_get_functiondef(v_canonical), 'UTF8')), 'hex');",
  "  IF v_sha IS DISTINCT FROM c_canonical_sha THEN",
  "    RAISE EXCEPTION 'TK_AQP_CANONICAL_DEFINITION: public.public_approve_quote definition changed (sha256 %)', v_sha USING ERRCODE = 'TKA05';",
  "  END IF;",
  "  SELECT (SELECT pg_catalog.string_agg(a::pg_catalog.text, ',' ORDER BY a::pg_catalog.text COLLATE pg_catalog.\"C\") FROM pg_catalog.unnest(p.proacl) AS a),",
  "         pg_catalog.pg_get_userbyid(p.proowner)::pg_catalog.text",
  "    INTO v_acl, v_owner",
  "    FROM pg_catalog.pg_proc p WHERE p.oid = v_canonical;",
  "  IF v_acl IS DISTINCT FROM c_canonical_acl OR v_owner IS DISTINCT FROM c_canonical_own THEN",
  "    RAISE EXCEPTION 'TK_AQP_CANONICAL_ACL: public.public_approve_quote ACL [%] owner [%] changed', v_acl, v_owner USING ERRCODE = 'TKA06';",
  "  END IF;",
  "END",
  "$tk_aqp_post$;",
  "$tk_stmt_7c9c1fb54e7c_47a45349bc76$]);",
  "DO $tk_post$",
  "DECLARE cur jsonb; pre jsonb := '{\"database\":\"postgres\",\"serverVersionNum\":\"170006\",\"searchPath\":\"pg_catalog, pg_temp\",\"ledgerColumns\":[{\"name\":\"version\",\"type\":\"text\",\"nullable\":\"NO\"},{\"name\":\"statements\",\"type\":\"ARRAY\",\"nullable\":\"YES\"},{\"name\":\"name\",\"type\":\"text\",\"nullable\":\"YES\"}],\"ledgerVersions\":[\"20260827000000\",\"20260827000001\",\"202608270000015\",\"20260827000002\",\"20260827000003\",\"20260828000000\",\"20260831000000\",\"20260908000000\",\"20260917000000\",\"20260917000001\",\"20260917000002\",\"20260917000003\",\"20260922000000\",\"20260927000000\"],\"ledgerPriorForwardSha256\":\"97d2017ed55ce06ca4683973adc69e48372d87a74e9c60e5a26d8b3a60a1d729\",\"overloads\":[{\"signature\":\"approve_quote_public(uuid)\",\"defSha256\":\"b50d1c880ba4f260eeea7925c33ca49d1d2dbed76730b4ba69f3b7af2b0a9a31\",\"securityDefiner\":true,\"acl\":\"=X/postgres,anon=X/postgres,authenticated=X/postgres,postgres=X/postgres,service_role=X/postgres\",\"owner\":\"postgres\"},{\"signature\":\"approve_quote_public(uuid, text)\",\"defSha256\":\"e36067ab64ff0c8d52a5eb200e175565a160ba3cac1880b6924573197cf17d7b\",\"securityDefiner\":true,\"acl\":\"=X/postgres,anon=X/postgres,authenticated=X/postgres,postgres=X/postgres,service_role=X/postgres\",\"owner\":\"postgres\"}],\"dependents\":[],\"canonical\":{\"defSha256\":\"eab641c566ec6776c0f3a389e6ba80d7e7f204d1479194f681ca51e838aeb855\",\"acl\":\"anon=X/postgres,authenticated=X/postgres,postgres=X/postgres\",\"owner\":\"postgres\",\"securityDefiner\":true,\"config\":[\"search_path=public, pg_temp\"]},\"schemaObjects\":[\"con:public.business_quote_sequences_pkey\",\"con:public.business_quote_sequences_user_id_fkey\",\"con:public.business_settings_pkey\",\"con:public.business_settings_user_id_fkey\",\"con:public.business_settings_user_id_unique\",\"con:public.chat_logs_pkey\",\"con:public.clients_pkey\",\"con:public.clients_user_id_fkey\",\"con:public.expenses_pkey\",\"con:public.expenses_user_id_fkey\",\"con:public.quote_attachments_pkey\",\"con:public.quote_attachments_quote_id_fkey\",\"con:public.quote_item_measurements_item_quote_fkey\",\"con:public.quote_item_measurements_pkey\",\"con:public.quote_item_measurements_quote_id_fkey\",\"con:public.quote_items_calculation_method_check\",\"con:public.quote_items_id_quote_id_key\",\"con:public.quote_items_pkey\",\"con:public.quote_items_quantity_source_check\",\"con:public.quote_items_quote_id_fkey\",\"con:public.quote_items_section_quote_fkey\",\"con:public.quote_sections_id_quote_id_key\",\"con:public.quote_sections_pkey\",\"con:public.quote_sections_quote_id_fkey\",\"con:public.quote_storage_gc_bucket_id_storage_path_key\",\"con:public.quote_storage_gc_pkey\",\"con:public.quote_storage_gc_user_id_fkey\",\"con:public.quotecode_documents_pkey\",\"con:public.quotes_client_id_fkey\",\"con:public.quotes_pkey\",\"con:public.quotes_user_id_fkey\",\"con:public.quotes_user_quote_number_unique\",\"con:public.services_pkey\",\"con:public.trial_reminder_deliveries_attempt_check\",\"con:public.trial_reminder_deliveries_pkey\",\"con:public.trial_reminder_deliveries_stage_check\",\"con:public.trial_reminder_deliveries_status_check\",\"con:public.trial_reminder_deliveries_user_id_fkey\",\"fn:public.allocate_quote_number(uuid)\",\"fn:public.approve_quote_public(uuid)\",\"fn:public.approve_quote_public(uuid, text)\",\"fn:public.claim_trial_reminder(uuid, text)\",\"fn:public.complete_trial_reminder(uuid, text, uuid, text, text, text)\",\"fn:public.enqueue_quote_attachment_gc()\",\"fn:public.guard_business_settings_plan_trial()\",\"fn:public.guard_quote_child_immutability()\",\"fn:public.guard_quote_immutability()\",\"fn:public.guard_quote_immutability_delete()\",\"fn:public.handle_user_migration()\",\"fn:public.increment_quote_views(uuid)\",\"fn:public.is_admin()\",\"fn:public.is_issuer_tenant_member(uuid)\",\"fn:public.is_super_admin()\",\"fn:public.protect_quote_number_immutability()\",\"fn:public.public_approve_quote(uuid, text)\",\"fn:public.public_increment_quote_view(uuid)\",\"fn:public.quote_acceptance_expired(date, text, timestamp with time zone)\",\"fn:public.save_quote_atomic(uuid, boolean, jsonb, jsonb, jsonb, jsonb, jsonb, uuid[], uuid[], jsonb, jsonb, uuid[])\",\"fn:public.save_quote_atomic_version()\",\"fn:public.save_quote_structured(uuid, jsonb, jsonb, jsonb, uuid[], uuid[])\",\"fn:public.unsection_quote_items_on_section_delete()\",\"pol:public.business_quote_sequences.Super admins can view all quote sequences\",\"pol:public.business_settings.Admins can view all business settings\",\"pol:public.business_settings.Owners can manage business settings\",\"pol:public.business_settings.Restrict business_settings insert to role=user\",\"pol:public.business_settings.Restrict business_settings insert to safe free or legitimate tr\",\"pol:public.business_settings.Super admins can update all business settings\",\"pol:public.business_settings.Super admins can view all business settings\",\"pol:public.business_settings.Users can insert own settings\",\"pol:public.business_settings.Users can update own settings\",\"pol:public.chat_logs.Super admins can view all chat logs\",\"pol:public.clients.Owners can manage clients\",\"pol:public.expenses.Owners can manage expenses\",\"pol:public.expenses.Users can delete own expenses\",\"pol:public.expenses.Users can insert own expenses\",\"pol:public.expenses.Users can manage their own expenses\",\"pol:public.expenses.Users can update own expenses\",\"pol:public.expenses.Users can view own expenses\",\"pol:public.expenses.Users manage their own expenses\",\"pol:public.quote_attachments.Owners can manage quote attachments\",\"pol:public.quote_item_measurements.Owners can manage quote item measurements\",\"pol:public.quote_items.Owners can manage quote items\",\"pol:public.quote_sections.Owners can manage quote sections\",\"pol:public.quote_storage_gc.Owners ack own storage gc\",\"pol:public.quote_storage_gc.Owners read own storage gc\",\"pol:public.quotecode_documents.Allow public insert/select\",\"pol:public.quotecode_documents.Owners can manage documents\",\"pol:public.quotecode_documents.Public can view documents\",\"pol:public.quotes.Owners can manage quotes\",\"pol:public.services.Owners can manage services\",\"pol:storage.objects.Authenticated owners upload quote files\",\"pol:storage.objects.Owners delete own quote files\",\"pol:storage.objects.Owners read own quote files\",\"rel:auth.amr_id_pk:i\",\"rel:auth.audit_log_entries:r\",\"rel:auth.audit_log_entries_pkey:i\",\"rel:auth.audit_logs_instance_id_idx:i\",\"rel:auth.confirmation_token_idx:i\",\"rel:auth.custom_oauth_providers:r\",\"rel:auth.custom_oauth_providers_created_at_idx:i\",\"rel:auth.custom_oauth_providers_enabled_idx:i\",\"rel:auth.custom_oauth_providers_identifier_idx:i\",\"rel:auth.custom_oauth_providers_identifier_key:i\",\"rel:auth.custom_oauth_providers_pkey:i\",\"rel:auth.custom_oauth_providers_provider_type_idx:i\",\"rel:auth.email_change_token_current_idx:i\",\"rel:auth.email_change_token_new_idx:i\",\"rel:auth.factor_id_created_at_idx:i\",\"rel:auth.flow_state:r\",\"rel:auth.flow_state_created_at_idx:i\",\"rel:auth.flow_state_pkey:i\",\"rel:auth.identities:r\",\"rel:auth.identities_email_idx:i\",\"rel:auth.identities_pkey:i\",\"rel:auth.identities_provider_id_provider_unique:i\",\"rel:auth.identities_user_id_idx:i\",\"rel:auth.idx_auth_code:i\",\"rel:auth.idx_oauth_client_states_created_at:i\",\"rel:auth.idx_user_id_auth_method:i\",\"rel:auth.idx_users_created_at_desc:i\",\"rel:auth.idx_users_email:i\",\"rel:auth.idx_users_last_sign_in_at_desc:i\",\"rel:auth.idx_users_name:i\",\"rel:auth.instances:r\",\"rel:auth.instances_pkey:i\",\"rel:auth.mfa_amr_claims:r\",\"rel:auth.mfa_amr_claims_session_id_authentication_method_pkey:i\",\"rel:auth.mfa_challenge_created_at_idx:i\",\"rel:auth.mfa_challenges:r\",\"rel:auth.mfa_challenges_pkey:i\",\"rel:auth.mfa_factors:r\",\"rel:auth.mfa_factors_last_challenged_at_key:i\",\"rel:auth.mfa_factors_pkey:i\",\"rel:auth.mfa_factors_user_friendly_name_unique:i\",\"rel:auth.mfa_factors_user_id_idx:i\",\"rel:auth.mfa_recovery_code_sets:r\",\"rel:auth.mfa_recovery_code_sets_mfa_factor_id_key:i\",\"rel:auth.mfa_recovery_code_sets_pkey:i\",\"rel:auth.mfa_recovery_code_sets_user_id_key:i\",\"rel:auth.mfa_recovery_codes:r\",\"rel:auth.mfa_recovery_codes_pkey:i\",\"rel:auth.mfa_recovery_codes_set_id_idx:i\",\"rel:auth.oauth_auth_pending_exp_idx:i\",\"rel:auth.oauth_authorizations:r\",\"rel:auth.oauth_authorizations_authorization_code_key:i\",\"rel:auth.oauth_authorizations_authorization_id_key:i\",\"rel:auth.oauth_authorizations_pkey:i\",\"rel:auth.oauth_client_states:r\",\"rel:auth.oauth_client_states_pkey:i\",\"rel:auth.oauth_clients:r\",\"rel:auth.oauth_clients_deleted_at_idx:i\",\"rel:auth.oauth_clients_pkey:i\",\"rel:auth.oauth_consents:r\",\"rel:auth.oauth_consents_active_client_idx:i\",\"rel:auth.oauth_consents_active_user_client_idx:i\",\"rel:auth.oauth_consents_pkey:i\",\"rel:auth.oauth_consents_user_client_unique:i\",\"rel:auth.oauth_consents_user_order_idx:i\",\"rel:auth.one_time_tokens:r\",\"rel:auth.one_time_tokens_pkey:i\",\"rel:auth.one_time_tokens_relates_to_hash_idx:i\",\"rel:auth.one_time_tokens_token_hash_hash_idx:i\",\"rel:auth.one_time_tokens_user_id_token_type_key:i\",\"rel:auth.reauthentication_token_idx:i\",\"rel:auth.recovery_token_idx:i\",\"rel:auth.refresh_tokens:r\",\"rel:auth.refresh_tokens_id_seq:S\",\"rel:auth.refresh_tokens_instance_id_idx:i\",\"rel:auth.refresh_tokens_instance_id_user_id_idx:i\",\"rel:auth.refresh_tokens_parent_idx:i\",\"rel:auth.refresh_tokens_pkey:i\",\"rel:auth.refresh_tokens_session_id_revoked_idx:i\",\"rel:auth.refresh_tokens_token_unique:i\",\"rel:auth.refresh_tokens_updated_at_idx:i\",\"rel:auth.saml_providers:r\",\"rel:auth.saml_providers_entity_id_key:i\",\"rel:auth.saml_providers_pkey:i\",\"rel:auth.saml_providers_sso_provider_id_idx:i\",\"rel:auth.saml_relay_states:r\",\"rel:auth.saml_relay_states_created_at_idx:i\",\"rel:auth.saml_relay_states_for_email_idx:i\",\"rel:auth.saml_relay_states_pkey:i\",\"rel:auth.saml_relay_states_sso_provider_id_idx:i\",\"rel:auth.schema_migrations:r\",\"rel:auth.schema_migrations_pkey:i\",\"rel:auth.scim_tokens:r\",\"rel:auth.scim_tokens_expires_at_idx:i\",\"rel:auth.scim_tokens_pkey:i\",\"rel:auth.scim_tokens_revoked_at_idx:i\",\"rel:auth.scim_tokens_sso_provider_id_idx:i\",\"rel:auth.scim_tokens_token_hash_key:i\",\"rel:auth.scim_users:r\",\"rel:auth.scim_users_created_at_idx:i\",\"rel:auth.scim_users_deleted_at_idx:i\",\"rel:auth.scim_users_external_id_key:i\",\"rel:auth.scim_users_id_idx:i\",\"rel:auth.scim_users_pkey:i\",\"rel:auth.scim_users_sso_provider_id_idx:i\",\"rel:auth.scim_users_updated_at_idx:i\",\"rel:auth.scim_users_user_id_idx:i\",\"rel:auth.scim_users_user_name_idx:i\",\"rel:auth.scim_users_user_name_key:i\",\"rel:auth.sessions:r\",\"rel:auth.sessions_not_after_idx:i\",\"rel:auth.sessions_oauth_client_id_idx:i\",\"rel:auth.sessions_pkey:i\",\"rel:auth.sessions_user_id_idx:i\",\"rel:auth.sso_domains:r\",\"rel:auth.sso_domains_domain_idx:i\",\"rel:auth.sso_domains_pkey:i\",\"rel:auth.sso_domains_sso_provider_id_idx:i\",\"rel:auth.sso_providers:r\",\"rel:auth.sso_providers_pkey:i\",\"rel:auth.sso_providers_resource_id_idx:i\",\"rel:auth.sso_providers_resource_id_pattern_idx:i\",\"rel:auth.unique_phone_factor_per_user:i\",\"rel:auth.user_id_created_at_idx:i\",\"rel:auth.users:r\",\"rel:auth.users_email_partial_key:i\",\"rel:auth.users_instance_id_email_idx:i\",\"rel:auth.users_instance_id_idx:i\",\"rel:auth.users_is_anonymous_idx:i\",\"rel:auth.users_phone_key:i\",\"rel:auth.users_pkey:i\",\"rel:auth.webauthn_challenges:r\",\"rel:auth.webauthn_challenges_expires_at_idx:i\",\"rel:auth.webauthn_challenges_pkey:i\",\"rel:auth.webauthn_challenges_user_id_idx:i\",\"rel:auth.webauthn_credentials:r\",\"rel:auth.webauthn_credentials_credential_id_key:i\",\"rel:auth.webauthn_credentials_pkey:i\",\"rel:auth.webauthn_credentials_user_id_idx:i\",\"rel:public.business_quote_sequences:r\",\"rel:public.business_quote_sequences_pkey:i\",\"rel:public.business_settings:r\",\"rel:public.business_settings_id_seq:S\",\"rel:public.business_settings_pkey:i\",\"rel:public.business_settings_user_id_idx:i\",\"rel:public.business_settings_user_id_unique:i\",\"rel:public.chat_logs:r\",\"rel:public.chat_logs_pkey:i\",\"rel:public.clients:r\",\"rel:public.clients_pkey:i\",\"rel:public.expenses:r\",\"rel:public.expenses_pkey:i\",\"rel:public.quote_attachments:r\",\"rel:public.quote_attachments_pkey:i\",\"rel:public.quote_item_measurements:r\",\"rel:public.quote_item_measurements_pkey:i\",\"rel:public.quote_items:r\",\"rel:public.quote_items_id_quote_id_key:i\",\"rel:public.quote_items_pkey:i\",\"rel:public.quote_sections:r\",\"rel:public.quote_sections_id_quote_id_key:i\",\"rel:public.quote_sections_pkey:i\",\"rel:public.quote_storage_gc:r\",\"rel:public.quote_storage_gc_bucket_id_storage_path_key:i\",\"rel:public.quote_storage_gc_id_seq:S\",\"rel:public.quote_storage_gc_pkey:i\",\"rel:public.quotecode_documents:r\",\"rel:public.quotecode_documents_pkey:i\",\"rel:public.quotes:r\",\"rel:public.quotes_pkey:i\",\"rel:public.quotes_quote_number_seq:S\",\"rel:public.quotes_user_quote_number_unique:i\",\"rel:public.services:r\",\"rel:public.services_id_seq:S\",\"rel:public.services_pkey:i\",\"rel:public.trial_reminder_deliveries:r\",\"rel:public.trial_reminder_deliveries_pkey:i\",\"rel:storage.bname:i\",\"rel:storage.buckets:r\",\"rel:storage.buckets_analytics:r\",\"rel:storage.buckets_analytics_pkey:i\",\"rel:storage.buckets_analytics_unique_name_idx:i\",\"rel:storage.buckets_pkey:i\",\"rel:storage.buckets_vectors:r\",\"rel:storage.buckets_vectors_pkey:i\",\"rel:storage.idx_multipart_uploads_list:i\",\"rel:storage.idx_objects_bucket_id_name:i\",\"rel:storage.idx_objects_bucket_id_name_lower:i\",\"rel:storage.idx_objects_current_version:i\",\"rel:storage.idx_objects_delete_markers:i\",\"rel:storage.idx_objects_null_version:i\",\"rel:storage.migrations:r\",\"rel:storage.migrations_name_key:i\",\"rel:storage.migrations_pkey:i\",\"rel:storage.name_prefix_search:i\",\"rel:storage.objects:r\",\"rel:storage.objects_bucket_id_name_version_key:i\",\"rel:storage.objects_pkey:i\",\"rel:storage.s3_multipart_uploads:r\",\"rel:storage.s3_multipart_uploads_parts:r\",\"rel:storage.s3_multipart_uploads_parts_pkey:i\",\"rel:storage.s3_multipart_uploads_pkey:i\",\"rel:storage.vector_indexes:r\",\"rel:storage.vector_indexes_name_bucket_id_idx:i\",\"rel:storage.vector_indexes_pkey:i\",\"trg:auth.users.on_auth_user_created_migration\",\"trg:public.business_settings.guard_business_settings_plan_trial_update\",\"trg:public.quote_attachments.enqueue_quote_attachment_gc\",\"trg:public.quote_attachments.guard_quote_attachments_immutability\",\"trg:public.quote_item_measurements.guard_quote_item_measurements_immutability\",\"trg:public.quote_items.guard_quote_items_immutability\",\"trg:public.quote_sections.guard_quote_sections_immutability\",\"trg:public.quote_sections.unsection_quote_items_before_section_delete\",\"trg:public.quotes.guard_quote_immutability_delete_trigger\",\"trg:public.quotes.guard_quote_immutability_update\",\"trg:public.quotes.quotes_protect_quote_number\",\"trg:storage.buckets.enforce_bucket_name_length_trigger\",\"trg:storage.buckets.protect_bucket_control_insert\",\"trg:storage.buckets.protect_bucket_control_update\",\"trg:storage.buckets.protect_bucket_control_update_role\",\"trg:storage.buckets.protect_buckets_delete\",\"trg:storage.objects.protect_objects_delete\",\"trg:storage.objects.update_objects_updated_at\"],\"publicFunctionDefsSha256\":\"adb63fd4efa30adae6d64729e9d12a81e46063b222946ebd64c8fcfcfddce56a\",\"publicColumnsSha256\":\"e6c4406ac5921b19c29bba918f5c83200a938ba533fbc7da8d24354492472ded\",\"publicTableAclSha256\":\"d14da1d6ef5d0cb72ee7909fe17cc253b45fad59e857b1980676991f732ae6ce\"}'::jsonb;",
  "BEGIN",
  "  IF pg_catalog.current_setting('search_path') IS DISTINCT FROM 'pg_catalog, pg_temp' THEN RAISE EXCEPTION 'TK_POSTCONDITION: search_path changed inside the transaction'; END IF;",
  "  cur := (pg_catalog.json_build_object(",
  " 'database', pg_catalog.current_database(),",
  " 'serverVersionNum', pg_catalog.current_setting('server_version_num'),",
  " 'searchPath', pg_catalog.current_setting('search_path'),",
  " 'ledgerColumns', (SELECT coalesce(pg_catalog.json_agg(pg_catalog.json_build_object('name', (column_name)::pg_catalog.text, 'type', (data_type)::pg_catalog.text, 'nullable', (is_nullable)::pg_catalog.text) ORDER BY ordinal_position), '[]') FROM information_schema.columns WHERE table_schema = 'supabase_migrations' AND table_name = 'schema_migrations'),",
  " 'ledgerVersions', (SELECT coalesce(pg_catalog.json_agg(version ORDER BY version COLLATE \"C\"), '[]') FROM supabase_migrations.schema_migrations),",
  " 'ledgerPriorForwardSha256', (SELECT pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(statements[1], 'UTF8')), 'hex') FROM supabase_migrations.schema_migrations WHERE version = '20260927000000'),",
  " 'overloads', (SELECT coalesce(pg_catalog.json_agg(pg_catalog.json_build_object(",
  "     'signature', (p.proname)::pg_catalog.text || '(' || pg_catalog.oidvectortypes(p.proargtypes) || ')', 'defSha256', pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(pg_catalog.pg_get_functiondef(p.oid), 'UTF8')), 'hex'), 'securityDefiner', p.prosecdef,",
  "     'acl', (SELECT pg_catalog.string_agg(a::pg_catalog.text, ',' ORDER BY a::pg_catalog.text COLLATE \"C\") FROM pg_catalog.unnest(p.proacl) AS a), 'owner', pg_catalog.pg_get_userbyid(p.proowner)::pg_catalog.text) ORDER BY pg_catalog.oidvectortypes(p.proargtypes) COLLATE \"C\"), '[]')",
  "   FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'public' AND p.proname = 'approve_quote_public'),",
  " 'dependents', (SELECT coalesce(pg_catalog.json_agg(x ORDER BY x COLLATE \"C\"), '[]') FROM (",
  "     SELECT 'dep:' || (d.deptype)::pg_catalog.text || ':' || pg_catalog.pg_describe_object(d.classid, d.objid, d.objsubid) AS x FROM pg_catalog.pg_depend d WHERE d.refclassid = 'pg_catalog.pg_proc'::pg_catalog.regclass AND d.deptype IN ('n', 'a') AND d.refobjid IN (SELECT p.oid FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'public' AND p.proname = 'approve_quote_public')",
  "     UNION ALL SELECT 'trg:' || (t.tgname)::pg_catalog.text FROM pg_catalog.pg_trigger t WHERE t.tgfoid IN (SELECT p.oid FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'public' AND p.proname = 'approve_quote_public')",
  "     UNION ALL SELECT 'evt:' || (e.evtname)::pg_catalog.text FROM pg_catalog.pg_event_trigger e WHERE e.evtfoid IN (SELECT p.oid FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'public' AND p.proname = 'approve_quote_public')) s),",
  " 'canonical', (SELECT pg_catalog.json_build_object('defSha256', pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(pg_catalog.pg_get_functiondef(p.oid), 'UTF8')), 'hex'), 'acl', (SELECT pg_catalog.string_agg(a::pg_catalog.text, ',' ORDER BY a::pg_catalog.text COLLATE \"C\") FROM pg_catalog.unnest(p.proacl) AS a), 'owner', pg_catalog.pg_get_userbyid(p.proowner)::pg_catalog.text, 'securityDefiner', p.prosecdef, 'config', p.proconfig)",
  "   FROM pg_catalog.pg_proc p WHERE p.oid = pg_catalog.to_regprocedure('public.public_approve_quote(uuid,text)')),",
  " 'schemaObjects', (SELECT coalesce(pg_catalog.json_agg(o ORDER BY o COLLATE \"C\"), '[]') FROM (",
  "   SELECT 'rel:' || (n.nspname)::pg_catalog.text || '.' || (c.relname)::pg_catalog.text || ':' || (c.relkind)::pg_catalog.text AS o FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname IN ('public', 'auth', 'storage') AND c.relkind IN ('r', 'p', 'v', 'm', 'f', 'S', 'i')",
  "   UNION ALL SELECT 'fn:' || (n.nspname)::pg_catalog.text || '.' || (p.proname)::pg_catalog.text || '(' || pg_catalog.oidvectortypes(p.proargtypes) || ')' FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'public'",
  "   UNION ALL SELECT 'pol:' || (schemaname)::pg_catalog.text || '.' || (tablename)::pg_catalog.text || '.' || (policyname)::pg_catalog.text FROM pg_catalog.pg_policies WHERE schemaname IN ('public', 'storage')",
  "   UNION ALL SELECT 'trg:' || (n.nspname)::pg_catalog.text || '.' || (c.relname)::pg_catalog.text || '.' || (t.tgname)::pg_catalog.text FROM pg_catalog.pg_trigger t JOIN pg_catalog.pg_class c ON c.oid = t.tgrelid JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace WHERE NOT t.tgisinternal AND n.nspname IN ('public', 'auth', 'storage')",
  "   UNION ALL SELECT 'con:' || (n.nspname)::pg_catalog.text || '.' || (c.conname)::pg_catalog.text FROM pg_catalog.pg_constraint c JOIN pg_catalog.pg_namespace n ON n.oid = c.connamespace WHERE n.nspname = 'public'",
  " ) s),",
  " 'publicFunctionDefsSha256', (SELECT pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(coalesce(pg_catalog.string_agg((p.proname)::pg_catalog.text || '(' || pg_catalog.oidvectortypes(p.proargtypes) || ')=' || pg_catalog.md5(pg_catalog.pg_get_functiondef(p.oid)) || ':' || (coalesce(p.proacl::pg_catalog.text, ''))::pg_catalog.text, E'\\n' ORDER BY p.proname COLLATE \"C\", pg_catalog.oidvectortypes(p.proargtypes) COLLATE \"C\"), ''), 'UTF8')), 'hex') FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'public' AND p.prokind IN ('f', 'p') AND p.proname <> 'approve_quote_public'),",
  " 'publicColumnsSha256', (SELECT pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(coalesce(pg_catalog.string_agg((table_name)::pg_catalog.text || '.' || (column_name)::pg_catalog.text || ':' || (data_type)::pg_catalog.text || ':' || (is_nullable)::pg_catalog.text || ':' || (coalesce(column_default::pg_catalog.text, ''))::pg_catalog.text, E'\\n' ORDER BY table_name COLLATE \"C\", column_name COLLATE \"C\"), ''), 'UTF8')), 'hex') FROM information_schema.columns WHERE table_schema = 'public'),",
  " 'publicTableAclSha256', (SELECT pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(coalesce(pg_catalog.string_agg((c.relname)::pg_catalog.text || ':' || (c.relrowsecurity)::pg_catalog.text || ':' || (coalesce(c.relacl::pg_catalog.text, ''))::pg_catalog.text, E'\\n' ORDER BY c.relname COLLATE \"C\"), ''), 'UTF8')), 'hex') FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p', 'v', 'm'))",
  "))::jsonb;",
  "  IF (SELECT pg_catalog.array_agg(version ORDER BY version COLLATE \"C\") FROM supabase_migrations.schema_migrations) IS DISTINCT FROM ARRAY['20260827000000','20260827000001','202608270000015','20260827000002','20260827000003','20260828000000','20260831000000','20260908000000','20260917000000','20260917000001','20260917000002','20260917000003','20260922000000','20260927000000','20260929000000']::text[] THEN RAISE EXCEPTION 'TK_POSTCONDITION: ledger'; END IF;",
  "  IF (SELECT pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(statements[1], 'UTF8')), 'hex') || ':' || (pg_catalog.array_length(statements, 1))::pg_catalog.text FROM supabase_migrations.schema_migrations WHERE version = '20260929000000') IS DISTINCT FROM '7c9c1fb54e7ce99896b9ba49f17b0608c686c340faa65ecefbb78ef949929ef4:1' THEN RAISE EXCEPTION 'TK_POSTCONDITION: ledger statements are not exactly the file bytes'; END IF;",
  "  IF pg_catalog.jsonb_array_length(cur -> 'overloads') <> 0 THEN RAISE EXCEPTION 'TK_POSTCONDITION: approve_quote_public still present'; END IF;",
  "  IF (cur -> 'canonical') IS DISTINCT FROM (pre -> 'canonical') OR (cur -> 'canonical' ->> 'defSha256') IS DISTINCT FROM 'eab641c566ec6776c0f3a389e6ba80d7e7f204d1479194f681ca51e838aeb855' OR (cur -> 'canonical' ->> 'acl') IS DISTINCT FROM 'anon=X/postgres,authenticated=X/postgres,postgres=X/postgres' OR (cur -> 'canonical' ->> 'owner') IS DISTINCT FROM 'postgres' THEN RAISE EXCEPTION 'TK_POSTCONDITION: public_approve_quote changed'; END IF;",
  "  IF (cur -> 'publicFunctionDefsSha256') IS DISTINCT FROM (pre -> 'publicFunctionDefsSha256') OR (cur -> 'publicColumnsSha256') IS DISTINCT FROM (pre -> 'publicColumnsSha256') OR (cur -> 'publicTableAclSha256') IS DISTINCT FROM (pre -> 'publicTableAclSha256') THEN RAISE EXCEPTION 'TK_POSTCONDITION: another public object changed'; END IF;",
  "  -- profile-owned schema diff: removed = exactly the legacy overloads that existed at pre-state (2, or 0 on a TEST-shaped rehearsal), nothing added",
  "  IF (SELECT coalesce(pg_catalog.jsonb_agg(o ORDER BY o COLLATE \"C\"), '[]'::jsonb) FROM pg_catalog.jsonb_array_elements_text(pre -> 'schemaObjects') o WHERE o NOT IN ('fn:public.approve_quote_public(uuid)', 'fn:public.approve_quote_public(uuid, text)')) IS DISTINCT FROM (cur -> 'schemaObjects') THEN RAISE EXCEPTION 'TK_POSTCONDITION: schema diff is not exactly the removal of the legacy overloads'; END IF;",
  "END",
  "$tk_post$;",
  "COMMIT;",
  "",
].join("\n");

export const PRODUCTION_BUNDLE_SHA256: string = "aeb3d19e54a8efbb8cc392816ed241fc72a013eeb2e5a78830b67131748ed29e";

export const PRODUCTION_BUNDLE_META = Object.freeze({
  status: "READY",
  profileId: "aqp-drop-20260929000000",
  migrationFile: "20260929000000_drop_legacy_approve_quote_public.sql",
  migrationSha256: "7c9c1fb54e7ce99896b9ba49f17b0608c686c340faa65ecefbb78ef949929ef4",
  candidateCommit: "623ac1ee01995b071b5f0d9a8f3d6f1cef87cc23",
  targetKind: "PRODUCTION",
  targetRef: "ixabnzhjeqevtbhdfswv",
  prestateSchema: "tekango-migration-prestate/aqp-1",
  prestateArtifactSha256: "8cd9c09ef07034a32124481bf8fed163c7274c8ef1cb7e071b628f994350d90b",
  prestateCapturedAtUtc: "2026-09-30T17:56:31.715Z",
  captureSidecarSha256: "160ab6787f0d9da78327c8a9976f509c28fc8fa3bf0d89997b423a6121add95f",
  pinnedSessionSettings: "{\"DateStyle\":\"ISO, MDY\",\"IntervalStyle\":\"postgres\",\"TimeZone\":\"UTC\",\"bytea_output\":\"hex\",\"extra_float_digits\":\"0\"}",
  nonce: "47a45349bc76",
  dollarTag: "tk_stmt_7c9c1fb54e7c_47a45349bc76",
  nonceDerivation: "sha256(\"tekango-p0-aqp-0929-production-bundle/nonce/1\\n\" + migrationSha256 + \"\\n\" + prestateArtifactSha256 + \"\\n\" + targetRef)[0:12]",
  transformation: "buildAqpApplySql output (pinnedSessionSettings from the capture sidecar) with the single leading psql line removed",
  generator: "tkrtool-iron:scripts/mirror/build-aqp-production-bundle.mjs",
  generatorCommit: "7bb85184916bb927f278edaac97149824fcc8982",
});
